### ISSUE TITLE
cant get it to work, get this error

### ISSUE THREAD

**Issue by SIlVeR-650** [Intenzi/ShowdownReplayDownloader#5]
![Screenshot 2024-11-19 133117](https://github.com/user-attachments/assets/1538630a-eeac-452d-869e-abd0bc1b10fd)

**Comment by SIlVeR-650** [comment]
![Screenshot 2024-11-19 133330](https://github.com/user-attachments/assets/5c456024-1354-40ec-8a0a-cccbd6420259)
I got this and I tried all options by itself (when npm install)

**Comment by Intenzi** [comment]
Hello thankyou for writing in, this is happening due to the ?p2 option you have added at the end of your link.
I'll look into parsing arguments for the ps link, in the meanwhile please run the command without `?p2` at the end:-

`node download.js -l https://replay.pokemonshowdown.com/gen7draft-2212254515 --nochat`

**Comment by SIlVeR-650** [comment]
thank you for the quick response, 
I tried without the ?p2 (which was auto added, prob bcuz it was from my showdown account) and it worked...), ngl this thing is insane, I wanted to use it for YT vids, but manually recording every battle is just too much for some1 as lazy as me... (tho me being on the wrong side will be kinda annoying, but its still waaay better, Ill be waiting (no pressure)) 

SIlVeR-650

**Comment by Intenzi** [comment]
cheers
I have placed in the fix, you should be able to utilize your original link now. (`https://replay.pokemonshowdown.com/gen7draft-2212254515?p2`)

**Comment by SIlVeR-650** [comment]
thx for the quick fix,
and yeah it does indeed work with both sides now.

-SIlVeR-650
